{% set name = "pytest-variables" %}
{% set version = "1.9.0" %}
{% set hash_type = "sha256" %}
{% set hash = "f79851e4c92a94c93d3f1d02377b5ac97cc8800392e87d108d2cbfda774ecc2a" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.4.2

  run:
    - python
    - setuptools
    - pytest >=2.4.2

test:
  imports:
    - pytest_variables

about:
  home: https://github.com/pytest-dev/pytest-variables
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'pytest plugin for providing variables to tests/fixtures'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
