{% set name = "pytest-variables" %}
{% set version = "2.0.0" %}
{% set hash = "1c9e4fc321e33be7d1b352ac9cf20fdd2c39a8e4e6fa2dcd042aaf70ed516be7" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.4.2

  run:
    - python
    - setuptools
    - pytest >=2.4.2

test:
  imports:
    - pytest_variables

about:
  home: https://github.com/pytest-dev/pytest-variables
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin for providing variables to tests/fixtures

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
