{% set name = "pytest-variables" %}
{% set version = "1.8.0" %}
{% set hash_type = "sha256" %}
{% set hash = "a475fe559bf3a1cfce5a603f7b4112415e7a76716c99394c088f788f75cd276a" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.4.2

  run:
    - python
    - setuptools
    - pytest >=2.4.2

test:
  imports:
    - pytest_variables

about:
  home: https://github.com/pytest-dev/pytest-variables
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'pytest plugin for providing variables to tests/fixtures'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
