{% set name = "pytest-variables" %}
{% set version = "1.7.0" %}
{% set hash_type = "sha256" %}
{% set hash = "d333e1df272f9ef4bf45d8665ee46a4901b11ab52bf661e83174f42f2f83df39" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.4.2

  run:
    - python
    - setuptools
    - pytest >=2.4.2

test:
  imports:
    - pytest_variables

about:
  home: https://github.com/pytest-dev/pytest-variables
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'pytest plugin for providing variables to tests/fixtures'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
