{% set name = "pytest-variables" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-variables-{{ version }}.tar.gz
  sha256: 1c9e4fc321e33be7d1b352ac9cf20fdd2c39a8e4e6fa2dcd042aaf70ed516be7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - pytest >=3.0.0,<8.0.0

test:
  imports:
    - pytest_variables
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-variables
  license: MPL-2.0
  license_file: LICENSE
  summary: 'pytest plugin for providing variables to tests/fixtures'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
