travis:
  secure:
    BINSTAR_TOKEN: aMI90tlHG38aeWVfg9hsWwYyUJUM/ECy5xTlJnvjSI7/EUZmNQPvG0RyQZmcIdwyYE3Ag+W3ax9S/e6uqmWh53Fqg2MvE97/eHgoLdc3C4YlVymkMY+XxEzAHq/kqQS81y7Nm3CngUZ7bcNkSB4BcyoJRBkPD0qnuvfSZMd99gUB47FRvHmCx0eRIWSgwphRxBr55003VNcADHjmV3cGbFOVka4c/DYCPoWETgzvSOAue4S8zFwbeE/kqXY5LsYKbRiLheRLlSrHLz0/ir9gHkQzq2KMWXlaxRA+gd3kJbqfoaq2rWn1vB/IyBxw9kGjcOpNHI9bhbrgCGfsCXy+jMU6345HkBbcbaZPgXLLpCflscWtGG3WwdP0p7tXzazZKJnrriprVxoe3aoLl40LuJCGoALreGRXsfG8k8fum+wdhaU8N82cbO/TKwWShvorNtHTXEDFUOg3IaOKYoYbR17M/DePoapwe2ESO2bYyMf76YbzB1iu4GaU4qcxB2TzgOmuJ720tXTb3moT/P/czsaiSUdDwD5a+l5UHu5STHBk4VjLH6LLSqQNIje+d+D+1pZRINNqM/G7gn/Tf50d+PD7Ws6k3hJSPvzI5ohyDpPh+xhZko8GrMraRQX2LkoVZAIdkksdd1TH+ObuOX2PpMdDJh/NfF1llgCmyklj5M4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
