travis:
  secure:
    BINSTAR_TOKEN: D/Yjtpat3P00nbplCfVTe6YVRvVwyGURACXnsY0znOHtxDEnTdfHC58IwTNXoRW/37w8+QARUvAuYmZkeqFyWtNCZ+26HpySarZ4uhC12eUbh9O8B+bQQF3PYyiSo3WzwPHXvLf7oUeLo32sSukzbu+9JtufXRPM4IKpbg8u85L37hWNZfArn2zl+JY0Giqj/+rg33KprNo/tupkJh6v5hnmQ0XKflVYdl95J1JGw2V7xjV0Kt/w/oM+ljHWd7rvHfGvFMhbBkSG2jjrLqrj7BQrQ/GvIn5amtSApJWWXQJ+YrPFLGimTF1pb12Sgpi5bjUgbLqeah6ALgZmtKdVVdZ3eQU3TpEOeJhOrvs6AXU/wSPHT1XkFZD69xAnGow5+oja0MP0iGNfN6m7hxLtcrB1YpveTuQh2lHufWFklWxgWe9BlRxesBJhdxf2Gxg8kmNW6JPRYz141qBSsadyEEpZE0EmsUxKwD88wwS+wmt6q05mY1G2y4Gw1DvsOWNgMUQDtCIlDKWLrufkzSC1s11n/e5ZknR9Oe5iWy16rBtdBksMveKeqfgABFz3OM03qiJKFlUmYdA6Y1KeLjeMERTpffEoYh3y8LSMj9JLxw4BMlrh4+gtP1hVHKxPbzcJpLOtcpI2xxfIYA77dx2CdXIFUPCZJrChOMyhdnydaGc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
